import { Order } from "../types";

export default [] as Order[];
//   {
//     id: "123",
//     unit: "87",
//     region: "דרום",
//     comment: "מדים רגילים לא טאקטיים מידה ב",
//     subItems: [
//       {
//         id: "11",
//         subItemBoardId: 'sibi',
//         productId: "1",
//         productName: "מדים טקטיים",
//         quantity: 140,
//         status: undefined,
//         userId: undefined,
//       },
//       {
//         id: "22",
//         subItemBoardId: 'sibi',
//         productId: "2",
//         productName: "פנס ראש",
//         quantity: 200,
//         status: undefined,
//         userId: undefined,
//       },
//       {
//         id: "33",
//         subItemBoardId: 'sibi',
//         productId: "3",
//         productName: "לדרמן",
//         quantity: 51,
//         status: undefined,
//         userId: undefined,
//       },
//     ],
//   },
//   {
//     id: "1234",
//     unit: "חרוב",
//     region: "צפון",
//     comment: "נעלי הרים מידות 43-47",
//     subItems: [
//       {
//         id: "11",
//         subItemBoardId: 'sibi',
//         productId: "1",
//         productName: "תיקי לאו",
//         quantity: 20,
//         status: undefined,
//         userId: undefined,
//       },
//       {
//         id: "22",
//         subItemBoardId: 'sibi',
//         productId: "2",
//         productName: "קסדות טקטיות",
//         quantity: 56,
//         status: undefined,
//         userId: undefined,
//       },
//       {
//         id: "33",
//         subItemBoardId: 'sibi',
//         productId: "3",
//         productName: "נעלי הרים",
//         quantity: 35,
//         status: undefined,
//         userId: undefined,
//       },
//     ],
//   },
//   {
//     id: "12345",
//     unit: "איסוף קרבי",
//     region: "דרום",
//     comment: "כפפות ממידות גדולות בלבד",
//     subItems: [
//       {
//         id: "11",
//         subItemBoardId: 'sibi',
//         productId: "1",
//         productName: "שלוקרים",
//         quantity: 47,
//         status: undefined,
//         userId: undefined,
//       },
//       {
//         id: "22",
//         subItemBoardId: 'sibi',
//         productId: "2",
//         productName: "כפפות טקטיות",
//         quantity: 47,
//         status: undefined,
//         userId: undefined,
//       },
//    ],
//  },
